insert = (
    "INSERT INTO CENTAURO ("
        "fk_cidade, "
        "ranking_centauro_receita_online_per_capita, "
        "centauro_market_share, "
        "centauro_atratividade_market, "
        "consumo_total_tenis_artigos_esportivos, "
        "centauro_receita_online_per_capita, "
        "centauro_receita_total_online_lj_fisicas, "
        "centauro_receita_lj_fisicas, "
        "centauro_receita_online_2019, "
        "centauro_receita_online_2020, "
        "percentual_crescimento_digital, "
        "centauro_pedido_online, "
        "centauro_pedidos_lj_fisicas, "
        "centauro_ticket_medio, "
        "max_prazo_realizado, "
        "min_prazo_realizado, "
        "q2_prazo_realizado, "
        "q3_prazo_realizado, "
        "avg_prazo_realizado, "
        "max_frete_pago, "
        "min_frete_pago, "
        "q2_frete_pago, "
        "q3_frete_pago, "
        "avg_frete_pago"
    ") VALUES ("
        "%(cidade_uf)s, "
        "%(ranking_centauro_receita_online_per_capita)s, "
        "%(centauro_market_share)s, "
        "%(centauro_atratividade_market)s, "
        "%(consumo_total_tenis_artigos_esportivos)s, "
        "%(centauro_receita_online_per_capita)s, "
        "%(centauro_receita_total_online_lj_fisicas)s, "
        "%(centauro_receita_lj_fisicas)s, "
        "%(centauro_receita_online_2019)s, "
        "%(centauro_receita_online_2020)s, "
        "%(percentual_crescimento_digital)s, "
        "%(centauro_pedido_online)s, "
        "%(centauro_pedidos_lj_fisicas)s, "
        "%(centauro_ticket_medio)s, "
        "%(max_prazo_realizado)s, "
        "%(min_prazo_realizado)s, "
        "%(q2_prazo_realizado)s, "
        "%(q3_prazo_realizado)s, "
        "%(avg_prazo_realizado)s, "
        "%(max_frete_pago)s, "
        "%(min_frete_pago)s, "
        "%(q2_frete_pago)s, "
        "%(q3_frete_pago)s, "
        "%(avg_frete_pago)s"
    ");"
)