insert = (
    "INSERT INTO POPULACAO ("
        "fk_cidade, "
        "cod_cidade_ibge, "
        "populacao_estimada, "
        "pib_per_capita, "
        "densidade_demografica, "
        "teledensidade, "
        "idhm, "
        "escolarizacao, "
        "mortalidade_infantil, "
        "ranking_populacao, "
        "ranking_atratividade_market, "
        "ranking_digitalizacao_teledensidade, "
        "ranking_oportunidade_logistica_prazo, "
        "ranking_pib_per_capita"
    ") VALUES ("
        "%(cidade_uf)s, "
        "%(cod_cidade_ibge)s, "
        "%(populacao_estimada)s, "
        "%(pib_per_capita)s, "
        "%(densidade_demografica)s, "
        "%(teledensidade)s, "
        "%(idhm)s, "
        "%(escolarizacao)s, "
        "%(mortalidade_infantil)s, "
        "%(ranking_populacao)s, "
        "%(ranking_atratividade_market)s, "
        "%(ranking_digitalizacao_teledensidade)s, "
        "%(ranking_oportunidade_logistica_prazo)s, "
        "%(ranking_pib_per_capita)s"
    ");"
)