column_names = {
    "Cidade_UF": "cidade_uf",
    "Cidade": "cidade",
    "UF": "uf",
    "Micro-Região": "micro_regiao",
    "cidade_estado_ddd_principal": "cidade_ddd_principal",
    "Área Territorial - km² [2018]": "area_territorial",
    "cod_municipio_uf": "cod_cidade_ibge",
    "População estimada - pessoas [2019]": "populacao_estimada",
    "PIB per capita - R$ [2017]": "pib_per_capita",
    "Densidade demográfica - hab/km² [2010]": "densidade_demografica",
    "teledensidade_nov-19": "teledensidade",
    "IDHM Índice de desenvolvimento humano municipal [2010]": "idhm",
    "Escolarização 6 a 14 anos - % [2010]": "escolarizacao",
    "Mortalidade infantil - óbitos por mil nascidos vivos [2017]": "mortalidade_infantil",
    "ranking_populacao": "ranking_populacao",
    "ranking_atratividade_market": "ranking_atratividade_market",
    "ranking_digitalizacao_teledensidade": "ranking_digitalizacao_teledensidade",
    "ranking_oportunidade_logistica_prazo": "ranking_oportunidade_logistica_prazo",
    "ranking_pib_per_capita": "ranking_pib_per_capita",
    "num_shoppings": "numero_shoppings",
    "num_shoppings_com_centauro": "numero_shoppings_com_centauro",
    "presenca_centauro_shoppings_cidade": "presenca_centauro_shoppings_cidade",
    "MagaLU": "presenca_magalu",
    "Americanas": "presenca_americanas",
    "delivery_online": "taxa_delivery_online",
    "ranking_centauro_receita_online_per_capita": "ranking_centauro_receita_online_per_capita",
    "centauro_market_share_2020": "centauro_market_share",
    "centauro_atratividade_market_2020": "centauro_atratividade_market",
    "Consumo Total Tenis e Artigos esportivos (R$)": "consumo_total_tenis_artigos_esportivos",
    "centauro_receita_online_per_capita": "centauro_receita_online_per_capita",
    "centauro_receita_total_online_lj_fisicas_2020": "centauro_receita_total_online_lj_fisicas",
    "centauro_receita_lj_fisicas_2020": "centauro_receita_lj_fisicas",
    "centauro_receita_online_2019": "centauro_receita_online_2019",
    "centauro_receita_online_2020": "centauro_receita_online_2020",
    " Perc Crescimento Digital": "percentual_crescimento_digital",
    "centauro_pedido_online_2020": "centauro_pedido_online",
    "centauro_pedidos_lj_fisicas_2020": "centauro_pedidos_lj_fisicas",
    "centauro_ticket_medio_2020": "centauro_ticket_medio",
    "max_prazo_realizado": "max_prazo_realizado",
    "min_prazo_realizado": "min_prazo_realizado",
    "q2_prazo_realizado": "q2_prazo_realizado",
    "q3_prazo_realizado": "q3_prazo_realizado",
    "avg_prazo_realizado": "avg_prazo_realizado",
    "max_frete_pago": "max_frete_pago",
    "min_frete_pago": "min_frete_pago",
    "q2_frete_pago": "q2_frete_pago",
    "q3_frete_pago": "q3_frete_pago",
    "avg_frete_pago": "avg_frete_pago"
}